<?php
require_once('masterpage/masterpage.php');

function contenedor()
{
?>
	<main>
		<section class="contenedor sobre-nosotros">
			<h2 class="titulo">Principios SOLID</h2>
			<div class="contenedor-sobre-nosotros">
				<img src="img/animacioncoding.svg" alt="" class="imagen-about-us">
				<div class="contenido-textos">
					<h3><span>1</span>Single Responsability Principle (SRP)</h3>
					<p>El principio de responsabilidad única se basa en que cada clase o método sólo debe hacer una cosa, sencilla y concreta</p>
					<h3><span>2</span>Open / Closed Principle</h3>
					<p>El principio Open/Closed dice que una clase/método debe estar abierto a extensiones pero cerrado a modificaciones.</p>
					<h3><span>3</span>Liskov Substitution Principle</h3>
					<p>Este principio trata sobre que los objetos de un desarrollo deberían ser reemplazables por instancias de sus subtipos sin alterar el correcto funcionamiento del desarrollo. Dicho de otro modo: cualquier subclase debería poder ser sustituible por la clase padre.</p>
					<h3><span>4</span>Interface Segregation Principle</h3>
					<p>Este principio trata sobre algo parecido a SRP. Es mejor definir una serie de métodos abstractos a través de una serie de interfaces para que implementen nuestras clases.
						Cada interface tendrá una única responsabilidad. Es preferible tener muchas interfaces que contengan pocos métodos que tener un interface con muchos métodos.</p>
					<h3><span>5</span>Dependency Inversion Principle</h3>
					<p>El objetivo de este principio es conseguir desacoplar las clases de nuestro desarrollo. Que una clase pueda funcionar por sí sola sin depender de otra.</p>
				</div>
			</div>
		</section>

		<section class="clientes contenedor">
			<h2 class="titulo">Ejemplos</h2>
			<div class="cards">

				<div class="card">

					<img src="img/img1rpu.png" alt="">

					<div class="contenido-texto-card">
						<h4>Single Responsability Principle (SRP)</h4>

					</div>
				</div>

			</div>
			<div class="cards">
				<div class="card">
					<img src="img/openClosed.jpg" alt="">
					<div class="contenido-texto-card">
						<h4>Open / Closed Principle</h4>

					</div>
				</div>
			</div>
			<div class="cards">
				<div class="card">
					<img src="img/liskov.jpg" alt="">
					<div class="contenido-texto-card">
						<h4>Liskov Substitution Principle</h4>

					</div>
				</div>

			</div>
			<div class="cards">
				<div class="card">
					<img src="img/interfacesegracion.jpg" alt="">
					<div class="contenido-texto-card">
						<h4>Interface Segregation Principle</h4>

					</div>
				</div>

			</div>
			<div class="cards">
				<div class="card">
					<img src="img/pimg2.png" alt="">
					<div class="contenido-texto-card">
						<h4>Dependency Inversion Principle</h4>

					</div>
				</div>
			</div>
		</section>

	</main>

<?php
};
?>

