<?php
require_once '../header.phtml';
?>

<main>
	<section class="contenedor sobre-nosotros">
		<h2 class="titulo">Nuestro producto</h2>
		<div class="contenedor-sobre-nosotros">
			<img src="img/ilustracion2.svg" alt="" class="imagen-about-us">
			<div class="contenido-textos">
				<h3><span>1</span>Los mejores productos</h3>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt veniam eius aspernatur ad
					consequuntur aperiam minima sed dicta odit numquam sapiente quam eum, architecto animi pariatur,
					velit doloribus laboriosam ut.</p>
				<h3><span>2</span>Los mejores productos</h3>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt veniam eius aspernatur ad
					consequuntur aperiam minima sed dicta odit numquam sapiente quam eum, architecto animi pariatur,
					velit doloribus laboriosam ut.</p>
			</div>
		</div>
	</section>
	<section class="portafolio">
		<div class="contenedor">
			<h2 class="titulo">Portafolio</h2>
			<div class="galeria-port">
				<div class="imagen-port">
					<img src="img/img1.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img2.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img3.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img1.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img4.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img5.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img6.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img7.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p>Nuestro trabajo</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="clientes contenedor">
		<h2 class="titulo">Que dicen nuestros clientes</h2>
		<div class="cards">
			<div class="card">
				<img src="img/face1.jpg" alt="">
				<div class="contenido-texto-card">
					<h4>Name</h4>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, sapiente!</p>
				</div>
			</div>
			<div class="card">
				<img src="img/face2.jpg" alt="">
				<div class="contenido-texto-card">
					<h4>Name</h4>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, sapiente!</p>
				</div>
			</div>
		</div>
	</section>
	
</main>
<?php
require_once '../footer.phtml';
?>