<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Document</title>
</head>

<body>
	<div class="container">
		<div class="row">
			<div class="col-sm-8">
				<h1>Probabilidad de la casa de apuesta(PCA)</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-8">
				<form action="<?= URL ?>apuestas/casaApuesta" method="post">
					<div class="form-group">
						<label for="val1">Cuota</label>
						<input type="number" name="val1" id="val1" step="0.01" min="0" class="form-control" value="<?=$data['val1']?>">

					</div>

					<br>
					<div class="form-group">
						<button type="submit" class="btn btn-primary form-control">Enviar</button>
					</div>
				</form>

			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-8">

				Respuesta: <input type="int" class="form-control" value="<?= $data['rpta'] ?>" disabled>
				<label for=""> <?= $data['mbox'] ?></label>
				<div class="form-group">
					<a href="../apuestas" class="btn btn-success col-sm-4"> Volver</a>
				</div>
			</div>
		</div>
	</div>


</body>