<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<title>Document</title>
</head>

<body>
	<div class="container">
		<div class="row">
			<div class="col-sm-8">
				<h1>Esperanza Matematica</h1>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<form action="<?= URL ?>apuestas/casaApuesta" method="post">
					<div class="form-group">
						<label for="val1">Cuota</label>
						<input type="number" name="val1" id="val1" class="form-control" value="<?= $data['val1'] ?>">

					</div>
					
					<br>
					<div class="form-group">
						<button type="submit" class="btn btn-primary">Enviar</button>
					</div>
				</form>

			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-8">

				Respuesta: <input type="int" class="form-control" value="<?= $data['rpta'] ?>" disabled>
				<label for=""> <?= $data['mbox'] ?></label>
			</div>
		</div>
	</div>

	
</body>