<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
	<div class="row">
		<div class="col-sm-8">
			<h1>Ganancia Neta</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-8">
			<form action="">
				<div class="form-group">
					<label for="val1">Apuesta</label>
					<input type="number" name="val1" id="val1" min="0" required class="form-control" value="<?= $data['val1'] ?>">

				</div>
				<div class="form-group">
					<label for="val2">Cuota</label>
					<input type="number" name="val2" id="val2" min="0" required class="form-control" value="<?= $data['val2'] ?>">

				</div>
				<br>
				<div class="form-group">
					<button type="submit" class="btn btn-primary form-control">Enviar</button>
				</div>
			</form>

		</div>
	</div>

	<br>
	<div class="row">
		<div class="col-sm-8">

			Respuesta: <input type="int" class="form-control" value="<?= $data['rpta'] ?>" disabled>
			<label for=""> <?= $data['mbox'] ?></label>
			<div class="form-group">
				<a href="../apuestas" class="btn btn-success col-sm-4"> Volver</a></ </div>
			</div>
		</div>
	</div>

	<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->