<?php
require_once('masterpage/masterpage.php');

function contenedor()
{
?>
	<section class="portafolio">
		<div class="contenedor">
			<h2 class="titulo">Area de Apuestas</h2>
			<div class="galeria-port">
				<div class="imagen-port">
					<img src="img/img1.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p><a href="apuestas/casaApuesta"> Casa de apuestas</a></p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img2.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p><a href="apuestas/esperanzaMatematica">Esperanza Matematica</a></p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img3.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p><a href="apuestas/gananciaNeta"> Ganancia Neta</a></p>
					</div>
				</div>
				<div class="imagen-port">
					<img src="img/img1.jpg" alt="">
					<div class="hover-galeria">
						<img src="img/icono1.png" alt="">
						<p><a href="apuestas/retornoDeInvercion">Retorno de Inversion</a></p>
					</div>
				</div>
			</div>
		</div>
	</section>

<?php
};
?>


